<template>
    <span>The example demonstrates how to create PivotTable</span>
    <el-button @click="startProcessing">Start</el-button>
    <a v-if="downloadUrl" :href="downloadUrl" :download="downloadName">Click here to download the generated file</a>
</template>
<script>
import { ref } from 'vue';
export default {
    setup() {
        const downloadUrl = ref(null);
        const downloadName = ref('');

        const startProcessing = async () => {
            wasmModule = window.wasmModule;
            if (wasmModule) {
                // Load the ARIALUNI.TTF font file into the virtual file system (VFS)
                await wasmModule.FetchFileToVFS('ARIALUNI.TTF', '/Library/Fonts/', `${import.meta.env.BASE_URL}static/font/`);

                // Create a new workbook
                const book = wasmModule.Workbook.Create();
                // Get the first worksheet
                let sheet = book.Worksheets.get(0);
                // Set the value to the cells
                sheet.Range.get('A1').Value = 'Product';
                sheet.Range.get('B1').Value = 'Month';
                sheet.Range.get('C1').Value = 'Count';

                sheet.Range.get('A2').Value = 'SpireDoc';
                sheet.Range.get('A3').Value = 'SpireDoc';
                sheet.Range.get('A4').Value = 'SpireXls';
                sheet.Range.get('A5').Value = 'SpireDoc';
                sheet.Range.get('A6').Value = 'SpireXls';
                sheet.Range.get('A7').Value = 'SpireXls';

                sheet.Range.get('B2').Value = 'January';
                sheet.Range.get('B3').Value = 'February';
                sheet.Range.get('B4').Value = 'January';
                sheet.Range.get('B5').Value = 'January';
                sheet.Range.get('B6').Value = 'February';
                sheet.Range.get('B7').Value = 'February';

                sheet.Range.get('C2').Value = '10';
                sheet.Range.get('C3').Value = '15';
                sheet.Range.get('C4').Value = '9';
                sheet.Range.get('C5').Value = '7';
                sheet.Range.get('C6').Value = '8';
                sheet.Range.get('C7').Value = '10';

                //Add a PivotTable to the worksheet
                let dataRange = sheet.Range.get('A1:C7');
                let cache = book.PivotCaches.Add({ range: dataRange });
                let pt = sheet.PivotTables.Add('Pivot Table', sheet.Range.get({ row: 10, column: 5 }), cache);

                //Drag the fields to the row area.
                let pf = pt.PivotFields.get_Item('Product');
                pf.Axis = wasmModule.AxisTypes.Row;
                let pf2 = pt.PivotFields.get_Item('Month');
                pf2.Axis = wasmModule.AxisTypes.Row;
                //Drag the field to the data area.
                pt.DataFields.Add(pt.PivotFields.get_Item('Count'), 'SUM of Count', wasmModule.SubtotalTypes.Sum);
                //Set PivotTable style
                pt.BuiltInStyle = wasmModule.PivotBuiltInStyles.PivotStyleMedium12;

                //Autofit columns generated by the pivotTable
                pt.CalculateData();
                sheet.AutoFitColumn(5);
                sheet.AutoFitColumn(6);
                // Define the output file name
                const outputFileName = 'CreatePivotTable.xlsx';
                // Save the workbook to the specified path
                book.SaveToFile({
                    fileName: outputFileName,
                    version: wasmModule.ExcelVersion.Version2010,
                });

                // Read the saved file and convert to a Blob object
                const modifiedFileArray = wasmModule.FS.readFile(outputFileName);
                const modifiedFile = new Blob([modifiedFileArray], {
                    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                });

                // Download the file
                downloadName.value  = outputFileName;
                downloadUrl.value = URL.createObjectURL(modifiedFile);

                // Clean up resources
                book.Dispose();
            }
        };

        return {
            startProcessing,
            downloadName,
            downloadUrl,
        };
    },
};
</script>
